---
title: "HW_01"
author: "F. A. Barrios<br>ENES Juriquilla, UNAM<br>"
date: "`r Sys.Date()`"
output:
  rmdformats::html_clean:
    highlight: kate
---


```{r setup, include=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

# Tarea 01
## ÓRTESIS Y PRÓTESIS, Probabilidad y estadística
### Fernando A Barrios, Feb 2021

1. In a study of the oral home care practice and reasons for seeking dental care among individuals on renal dialysis,
Atassi studied 90 subjects on renal dialysis. The oral hygiene status of all subjects was examined using a plaque index 
with a range of 0 to 3 (0 = no soft plaque deposits, 3 = an abundance of soft plaque deposits). The data in `EXR_C02_S03_01.csv`,
shows the plaque index scores for all 90 subjects.  
(a) Use these data to prepare:  
	A frequency distribution  
	A relative frequency distribution  
	A cumulative frequency distribution  
	A histogram  
	A frequency polygon  
(b) What percentage of the measurements are less than 2.00?  
(c) What proportion of the subjects have measurements greater than or equal to 1.50?  
(d) What percentage of the measurements are between 1.50 and 1.99 inclusive?  
(e) How many of the measurements are greater than 2.49?  

2. Janardhan et al. conducted a study in which they measured identical intracranial aneurysms (IIAs) in 125 patients. The 
researchers examined postprocedural complications and concluded that IIAs can be safely treated without causing mortality 
with a lower complications rate than previously reported.  The data in `EXR_C02_S03_02.csv`, are the sizes (in millimeters) 
of the 159 IIAs in the sample.  
(a) Use these data to prepare:  
	A frequency distribution  
	A relative frequency distribution  
	A cumulative frequency distribution  
	A histogram  
	A frequency polygon  
(b) What percentage of the measurements are between 10 and 14.9 inclusive?  
(c) How many observations are less than 20?  
(d) What proportion of the measurements are greater than or equal to 25?  
(e) What percentage of the measurements are either less than 10.0 or greater than 19.95?  

3. Hoekema et al. studied the craniofacial morphology of patients diagnosed with obstructive sleep apnea syndrome (OSAS) in 
healthy male subjects. One of the demographic variables the researchers collected for all subjects was the Body Mass Index (BMI)
(calculated by dividing the weight in *kg* by the square of the patient’s height in *cm*) in `EXR_C02_s03_03.csv`, are the BMI 
values of 29 OSAS subjects,  
(a) Use these data to construct:  
	A frequency distribution  
	A relative frequency distribution  
	A cumulative frequency distribution  
	A cumulative relative frequency distribution  
	A histogram  
	A frequency polygon  
(b) What percentage of the measurements are less than 30?  
(c) What percentage of the measurements are between 40 and 49.99 inclusive?  
(d) What percentage of the measurements are greater than 34.99?  
(e) How many observations are less than 40?  

