---
title: "Introducción"
author: "F.A. Barrios"
date: "`r Sys.Date()`"
output:
  rmdformats::html_clean:
    highlight: kate
---


```{r setup, include=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="80")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=80)
```

# Instalación de R  
## En esta corta introducción describimos algunas ligas de instrucciones  

En las siguientes ligas encontrarán información de cómo instalar en sus máquinas el programa-lenguaje R, y el 
programa RStudio.  Ambos necesarios para trabajar los ejemplos, tareas y proyectos que se desarrollarán en clase.
El prograna R es un proyecto muy importante de "open code", "open access" y "open science", goza de una popularidad
extraordinaria, en particular en la comunidad académica mundial. Es de distribución abierta y por lo tanto tiene una
licencia de distribución pública, ademá cuneta con una inmensa cantidad de paquetes desarrollados para diferentes
proyectos, y cuenta con una importante cantidad de documentos públicos de ayuda. Como estos que se apuntan aquí.  


## Material en Inglés  
La realidad es que al ser un proyecto global, el material de trabajo y ayuda para R por lo general está en R, es decir el
material es en su gran mayoría en inglés, por lo que los invitamos a hacer un esfuerzo para trabajar los materiales
relacionados a R, uno de estos sitios sin duda es la misma página de [CRAN](https://cran.r-project.org/)   

Esta página de R-coder está muy buena y muy adecuada para el nivel del curso que estamos dando, se las recomiendo mucho [R-coder](https://r-coder.com/r-introduction/) Continuaré revisando material en la red para hacer recomendaciones en este sitio. Les sugiero que también ustedes hagan búsquedas de material referente a R.  Hay una cantidad muy importante de información y ejemplos del uso de R.  

Por ejemplo una página muy interesante para aprender a hacer gráficas con `ggplot` es: http://r-statistics.co/Top50-Ggplot2-Visualizations-MasterList-R-Code.html  

## Libro del curso  
El curso no tiene un libro de texto, pero en lo general pienso seguir las ideas del libro de W.W. Daniel, Biostatistics, 9th edition. En particular por los ejercicios y ejemplos, que tienen una buena cantidad de temas relacionados con los problemas biológicos y ejemplos con temas que encontrarán de interés.  También hay material que pueden accesar y si lo encuentran de interés pueden pagar su acceso libre, como el libro de [R in Action](https://livebook.manning.com/book/r-in-action-third-edition/copyright-2020-manning-publications/v-8/5).  


## Ligas en español  
La sigunete liga contine una serie de instrucciones en español para instalar la última versión de R y RStudio en
los sistemas Windows, LINUX (diferentes distribuciones, como UBUNTU entre otros) y MacOS.  

http://www.upm.es/sfs/Rectorado/Gabinete%20del%20Rector/Notas%20de%20Prensa/2015/05/documentos/Instrucciones%20de%20instalaci%C3%B3n%20de%20R%20y%20RStudio.pdf  

y en esta liga hay un vidéo 

https://www.youtube.com/watch?v=1WXgaa2Spp0

En mi página de GitHub hay una copia del manual de introducción a R en español de CRAN.  
