---
title: "HW_05"
author: "F. A. Barrios<br>ENES Juriquilla, UNAM<br>"
date: "`r Sys.Date()`"
output:
  rmdformats::html_clean:
    highlight: kate
---

```{r setup, include=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

# Tarea Probabilidad y Estadística (Tema V)  
## Lic. Tecnología ENES Juriquilla  
## F.A. Barrios  
### Teoría de la estimación

1. Analisis de gases arteriales en 15 sujetos activos físicamenete resultaron los siguientes datos de valores para $PaO_2$,  `c(75,80,80,74,84,78,89,72,83,76,75,87,78,79,88)`, estime el intervalo de conianza al 95 por ciento para el promedio de la población.  
2. Cual es el promedio en suero del nivel de bilirrubina para internar pacientes a un hospital para tratamiento de hepatítis? Un muestra de 10 pacientes reveló los siguientes resutlados: `c(20.5, 14.8, 21.3, 12.7, 15.2, 26.6, 23.4, 22.9, 15.7, 19.2)`. Construya el intervalo de concfianza al 95 por ciento de la población.  
3. Los niveles de $pH$ se determinaron para dos muestras aleatorias e independientes de niños de escuelas de $7^o$ grado. La muestra A fue de niños libres de caries mientras que la muestra B, los niños tenían un alto grado e icidencia de caries. Los resultados se listan en el archivo `REV_C06_22.csv`. Construya el intervalo de confianza al 90 por ciento para la diferencia del promedio de las poblaciones suponiendo que las varianzas son iguales.  
4. El medicamento A fue recetado aleatoriamente a una muetra de 12 sujetos que adolecian de insomnia. Una muestra independiente de 16 pacientes con el mismo problema de insomnia recibieron el medicamento B.  El número de horas de sueño que experimentaron los pacientes durante la seguna noche después del inicio del tratamiento se listan en el archivo `REV_C06_23.csv'. Construya el intervalo de confianza al 95 por ciento de la diferencia del promedio de las poblaciones, suponiendo que la varianza de las poblaciones son iguales.  
